version: "3"
services: 
    client:
        stdin_open: true
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "3000:9000"
        volumes: 
            - "/app/node_modules"
            - "./:/app"